"""
NetEase Cloud Music podcast playlist refresh script
Usage: python update_playlist.py
Fetches all programs from a DJ radio and updates playlist.json
"""

import json
import sys
import io
import os
import urllib.request
import urllib.error

# Fix encoding for Windows CMD
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

RADIO_ID = "1224027027"
API_URL = f"https://music.163.com/api/dj/program/byradio?radioId={RADIO_ID}&limit=200"
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_FILE = os.path.join(SCRIPT_DIR, "playlist.json")
JS_OUTPUT_FILE = os.path.join(SCRIPT_DIR, "_bgm_data.js")

HEADERS = {
    "Referer": "https://music.163.com/",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "Accept": "application/json, text/plain, */*",
}


def fetch_playlist():
    """Fetch program list from NetEase Cloud Music API"""
    req = urllib.request.Request(API_URL, headers=HEADERS)
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            if data.get("code") != 200:
                print(f"[ERROR] API returned code={data.get('code')}, message={data.get('message')}")
                return None
            return data["programs"]
    except urllib.error.URLError as e:
        print(f"[ERROR] Network request failed: {e}")
        return None
    except Exception as e:
        print(f"[ERROR] Parse failed: {e}")
        return None


def build_playlist(programs):
    """Convert raw program data to compact format"""
    result = []
    for p in programs:
        song = p.get("mainSong", {})
        artist = ""
        artists = song.get("artists", [])
        if artists:
            artist = artists[0].get("name", "")
        result.append({
            "programId": p.get("id"),
            "name": song.get("name", ""),
            "artist": artist,
            "songId": song.get("id"),
            "duration": song.get("duration", 0),
        })
    return result


def main():
    print(f"Fetching podcast playlist (radioId={RADIO_ID}) ...")
    programs = fetch_playlist()
    if not programs:
        sys.exit(1)

    playlist = {
        "radioId": RADIO_ID,
        "count": len(programs),
        "programs": build_playlist(programs),
    }

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(playlist, f, ensure_ascii=False, indent=2)

    # Also generate _bgm_data.js for browser to load via <script src>
    js_content = "/* Auto-generated by update_playlist.py - DO NOT EDIT */\n"
    js_content += "var __BGM_PLAYLIST__ = " + json.dumps(playlist["programs"], ensure_ascii=False) + ";\n"
    with open(JS_OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"[OK] Success! {len(programs)} programs saved to {OUTPUT_FILE}")
    print(f"     Also generated {JS_OUTPUT_FILE} ({len(js_content)} bytes)")
    print(f"  Preview (first 5):")
    for i, p in enumerate(playlist["programs"][:5]):
        print(f"    {i+1}. {p['name']} - {p['artist']} (programId={p['programId']})")


if __name__ == "__main__":
    main()
