"""
Bing Wallpaper Download & Logo Brightness Detection Script
Usage: python update_wallpaper.py [--force]
  1. Download today's Bing wallpaper (1920x1080)
  2. Crop Logo area from a copy using user-measured rectangle
  3. Compute WCAG relative luminance → dark/white logo decision
  4. Sync staging/ → prod/ (staging kept as permanent archive)
  5. Daily dedup: skip if already updated today (Beijing time)
     --force: bypass daily dedup (for manual workflow_dispatch)
"""
import json
import os
import re
import sys
import io
import shutil
import urllib.request
import urllib.error
import time
from datetime import datetime, timezone, timedelta
from io import BytesIO

# Fix encoding for Windows CMD
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

try:
    from PIL import Image
except ImportError:
    print("[ERROR] Pillow not installed. Run: pip install Pillow")
    sys.exit(1)

# ── Configuration ──────────────────────────────────────────────

API_META_URL = "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US"
API_FALLBACK = "https://api.dujin.org/bing/1920.php"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
STAGING_DIR = os.path.join(SCRIPT_DIR, "staging")
PROD_DIR = os.path.join(SCRIPT_DIR, "prod")
CONFIG_FILE = "logo_config.js"
WALLPAPER_FILE = "wallpaper.jpg"

# User-measured crop rectangle on 1920x1080 wallpaper
# cx=960, cy=305, w=400, h=160 → srcX=760, srcY=225
CROP_X = 760
CROP_Y = 225
CROP_W = 400
CROP_H = 160
CROP_FILE = "crop.jpg"

JPEG_QUALITY = 92

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
}


# ── Helpers ────────────────────────────────────────────────────

def download_wallpaper(url, timeout=30):
    """Download wallpaper bytes from URL, following redirects."""
    req = urllib.request.Request(url, headers=HEADERS)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            data = resp.read()
            if len(data) < 10 * 1024:
                raise ValueError(f"Image too small: {len(data)} bytes")
            return data
    except Exception as e:
        raise RuntimeError(f"Download failed: {e}")


def get_bing_image_url(meta_url=API_META_URL, timeout=15):
    """Fetch today's wallpaper URL from Bing official JSON API.
    Returns (image_url, title) tuple."""
    req = urllib.request.Request(meta_url, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        meta = json.loads(resp.read().decode("utf-8"))
    img = meta["images"][0]
    base = "https://www.bing.com"
    return (base + img["url"], img.get("title", ""))


def compute_brightness(crop_img):
    """Compute WCAG relative luminance of a cropped image.
    Only counts pixels with alpha >= 128.
    Returns (average_luminance, pixel_count).
    """
    if crop_img.mode == "RGBA":
        pixels = list(crop_img.getdata())
    else:
        pixels = [(r, g, b, 255) for (r, g, b) in crop_img.getdata()]

    total = 0.0
    count = 0
    for r, g, b, a in pixels:
        if a < 128:
            continue
        # WCAG Relative Luminance = 0.2126R + 0.7152G + 0.0722B
        total += 0.2126 * r + 0.7152 * g + 0.0722 * b
        count += 1

    if count == 0:
        return 0.0, 0
    return total / count, count


def beijing_date():
    """Return today's date string in Beijing time (UTC+8)."""
    return (datetime.now(timezone.utc) + timedelta(hours=8)).strftime("%Y-%m-%d")


def should_skip_today():
    """Return True if logo_config.js already has today's Beijing date (= already updated)."""
    config_path = os.path.join(STAGING_DIR, CONFIG_FILE)
    if not os.path.exists(config_path):
        return False
    try:
        with open(config_path, 'r', encoding='utf-8') as f:
            content = f.read()
        match = re.search(r'"date"\s*:\s*"(\d{4}-\d{2}-\d{2})"', content)
        if not match:
            return False
        if match.group(1) == beijing_date():
            print(f"Already updated today ({beijing_date()} Beijing time), skipping.")
            return True
        return False
    except Exception as e:
        print(f"Dedup check failed ({e}), proceeding anyway.")
        return False


def write_config(brightness, pixel_count, img_w, img_h):
    """Write logo_config.js to staging directory (brightness data only, threshold decided locally)."""
    config = {
        "date": beijing_date(),
        "wallpaper_raw_w": img_w,
        "wallpaper_raw_h": img_h,
        "brightness": round(brightness, 1),
        "pixel_count": pixel_count,
        "crop": {"x": CROP_X, "y": CROP_Y, "w": CROP_W, "h": CROP_H},
        "formula": "WCAG Relative (0.2126R + 0.7152G + 0.0722B)",
    }
    content = "/* Auto-generated by update_wallpaper.py - DO NOT EDIT */\n"
    content += "var __LOGO_CONFIG__ = " + json.dumps(config, ensure_ascii=False) + ";\n"
    os.makedirs(STAGING_DIR, exist_ok=True)
    path = os.path.join(STAGING_DIR, CONFIG_FILE)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


# ── Main ───────────────────────────────────────────────────────

def main():
    # 0. Daily dedup — skip if already updated today (Beijing time)
    #    --force bypasses this check (used by workflow_dispatch)
    force = '--force' in sys.argv
    if not force and should_skip_today():
        return

    # 1. Download wallpaper
    print("Downloading wallpaper...")
    try:
        # Step 1a: get today's image URL from Bing official API
        img_url, title = get_bing_image_url()
        print(f"  Bing title: {title}")
        print(f"  Image URL: {img_url}")
        img_bytes = download_wallpaper(img_url)
        print(f"  OK {len(img_bytes) // 1024} KB from Bing official")
    except Exception as e:
        print(f"  Bing official failed: {e}")
        print(f"  Trying fallback (dujin.org)...")
        try:
            img_bytes = download_wallpaper(API_FALLBACK)
            print(f"  OK {len(img_bytes) // 1024} KB from fallback API")
        except Exception as e2:
            print(f"[FATAL] Both APIs failed. Fallback: {e2}")
            sys.exit(1)

    # 2. Open image & verify resolution
    img = Image.open(BytesIO(img_bytes))
    raw_w, raw_h = img.size
    print(f"Wallpaper size: {raw_w}x{raw_h}")
    if (raw_w, raw_h) != (1920, 1080):
        print(f"  [WARN] Non-standard resolution (expected 1920x1080)")

    # 3. Save original wallpaper to staging/
    os.makedirs(STAGING_DIR, exist_ok=True)
    wallpaper_path = os.path.join(STAGING_DIR, WALLPAPER_FILE)
    if img.mode == "RGBA":
        img = img.convert("RGB")
    img.save(wallpaper_path, "JPEG", quality=JPEG_QUALITY)
    print(f"  OK Saved to staging/wallpaper.jpg")

    # 4. Copy & crop the Logo region (clone → crop, original untouched)
    crop = img.copy().crop((CROP_X, CROP_Y, CROP_X + CROP_W, CROP_Y + CROP_H))
    brightness, pixel_count = compute_brightness(crop)
    print(f"Crop region ({CROP_X},{CROP_Y},{CROP_W},{CROP_H}): brightness={brightness:.1f} ({pixel_count} px)")

    # Save cropped image to staging/
    crop_path = os.path.join(STAGING_DIR, CROP_FILE)
    if crop.mode == "RGBA":
        crop = crop.convert("RGB")
    crop.save(crop_path, "JPEG", quality=JPEG_QUALITY)
    print(f"  OK Saved to staging/{CROP_FILE}")

    # 5. Log brightness result (threshold decision is left to browser-side JS)
    print(f"Brightness: {brightness:.1f}")

    # 6. Write logo_config.js to staging/ (data only, no logo/foot_color)
    write_config(brightness, pixel_count, raw_w, raw_h)
    print(f"  OK Wrote staging/{CONFIG_FILE}")

    # 7. Sync staging/ → prod/ (staging stays as permanent archive)
    #    Clear prod/ first, then copy all staging files in
    if os.path.exists(PROD_DIR):
        for item in os.listdir(PROD_DIR):
            item_path = os.path.join(PROD_DIR, item)
            if os.path.isfile(item_path):
                os.remove(item_path)
    else:
        os.makedirs(PROD_DIR)

    for item in os.listdir(STAGING_DIR):
        src = os.path.join(STAGING_DIR, item)
        dst = os.path.join(PROD_DIR, item)
        if os.path.isfile(src):
            shutil.copy2(src, dst)

    print(f"\n[OK] staging/ synced → prod/ (staging kept for archive)")
    print(f"     {WALLPAPER_FILE} | {CROP_FILE} | {CONFIG_FILE}")


if __name__ == "__main__":
    main()
