"""
Bing Wallpaper Download & Logo Brightness Detection Script
Usage: python update_wallpaper.py
- Downloads today's Bing wallpaper (1920x1080)
- Crops Logo area from a copy of the original
- Computes WCAG relative luminance per viewport
- Atomically replaces staging/ → prod/
"""

import json
import os
import sys
import io
import shutil
import urllib.request
import urllib.error
import time
from io import BytesIO

# Fix encoding for Windows CMD
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

from statistics import median

try:
    from PIL import Image
except ImportError:
    print("[ERROR] Pillow not installed. Run: pip install Pillow")
    sys.exit(1)

# ── Configuration ──────────────────────────────────────────────

API_URL = "https://api.dujin.org/bing/1920.php"
API_FALLBACK = "https://bing.bitdata.top/api/wallpaper?format=image"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
STAGING_DIR = os.path.join(SCRIPT_DIR, "staging")
PROD_DIR = os.path.join(SCRIPT_DIR, "prod")
CONFIG_FILE = "logo_config.js"
WALLPAPER_FILE = "wallpaper.jpg"

# Logo sampling rectangle on the raw 1920x1080 wallpaper (pixels)
# User-measured: cx=960, cy=305, w=400, h=160
BENCHMARK_CX = 960
BENCHMARK_CY = 305
BENCHMARK_W = 400
BENCHMARK_H = 160

# srcX = cx - w/2 = 760, srcY = cy - h/2 = 225
SRC_X = BENCHMARK_CX - BENCHMARK_W // 2
SRC_Y = BENCHMARK_CY - BENCHMARK_H // 2
SRC_W = BENCHMARK_W
SRC_H = BENCHMARK_H

# Viewports to verify consistency (cover+center auto-derives crop region)
VIEWPORTS = [
    {"name": "1920x1080@1x",   "vp_w": 1920, "vp_h": 1080, "dpi_scale": 1.0},
    {"name": "1536x864@1.25x", "vp_w": 1536, "vp_h": 864,  "dpi_scale": 1.25},
    {"name": "1280x720@1.5x",  "vp_w": 1280, "vp_h": 720,  "dpi_scale": 1.5},
    {"name": "2560x1440@1x",   "vp_w": 2560, "vp_h": 1440, "dpi_scale": 1.0},
    {"name": "1920x1080@2x",   "vp_w": 1920, "vp_h": 1080, "dpi_scale": 2.0},
]

BRIGHTNESS_THRESHOLD = 150      # >= 150 → dark logo, < 150 → white logo
JPEG_QUALITY = 92

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
}

# ── Helpers ────────────────────────────────────────────────────

def download_wallpaper(url, timeout=30):
    """Download wallpaper bytes from URL, following redirects."""
    req = urllib.request.Request(url, headers=HEADERS)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            data = resp.read()
            if len(data) < 10 * 1024:
                raise ValueError(f"Image too small: {len(data)} bytes")
            return data
    except Exception as e:
        raise RuntimeError(f"Download failed: {e}")


def compute_brightness(crop_img):
    """Compute WCAG relative luminance of an image region.
    Only counts pixels with alpha >= 128.
    Returns (average_luminance, pixel_count).
    """
    if crop_img.mode == "RGBA":
        pixels = list(crop_img.getdata())
    else:
        pixels = [(r, g, b, 255) for (r, g, b) in crop_img.getdata()]

    total = 0.0
    count = 0
    for r, g, b, a in pixels:
        if a < 128:
            continue
        # WCAG Relative Luminance
        total += 0.2126 * r + 0.7152 * g + 0.0722 * b
        count += 1
    if count == 0:
        return 0.0, 0
    return total / count, count


def write_config(samples, overall_brightness, logo, img_w, img_h):
    """Write logo_config.js to staging directory."""
    config = {
        "date": time.strftime("%Y-%m-%d", time.gmtime()),
        "wallpaper_raw_w": img_w,
        "wallpaper_raw_h": img_h,
        "logo": logo,
        "foot_color": "rgba(0, 0, 0, 0.8)" if logo == "dark" else "rgba(255, 255, 255, 0.8)",
        "brightness": round(overall_brightness, 1),
        "threshold": BRIGHTNESS_THRESHOLD,
        "formula": "WCAG Relative (0.2126R + 0.7152G + 0.0722B)",
        "samples": samples,
    }
    content = "/* Auto-generated by update_wallpaper.py - DO NOT EDIT */\n"
    content += "var __LOGO_CONFIG__ = " + json.dumps(config, ensure_ascii=False) + ";\n"
    os.makedirs(STAGING_DIR, exist_ok=True)
    path = os.path.join(STAGING_DIR, CONFIG_FILE)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


# ── Main ───────────────────────────────────────────────────────

def main():
    # 1. Download wallpaper
    print("Downloading wallpaper...")
    try:
        img_bytes = download_wallpaper(API_URL)
        print(f"  OK {len(img_bytes) // 1024} KB from primary API")
    except Exception as e:
        print(f"  Primary API failed: {e}")
        print(f"  Trying fallback...")
        try:
            img_bytes = download_wallpaper(API_FALLBACK)
            print(f"  OK {len(img_bytes) // 1024} KB from fallback API")
        except Exception as e2:
            print(f"[FATAL] Both APIs failed. Fallback: {e2}")
            sys.exit(1)

    # 2. Open image & verify resolution
    img = Image.open(BytesIO(img_bytes))
    raw_w, raw_h = img.size
    print(f"Wallpaper size: {raw_w}x{raw_h}")
    if (raw_w, raw_h) != (1920, 1080):
        print(f"  [WARN] Non-standard resolution (expected 1920x1080)")

    # 3. Save original wallpaper to staging/
    os.makedirs(STAGING_DIR, exist_ok=True)
    wallpaper_path = os.path.join(STAGING_DIR, WALLPAPER_FILE)
    if img.mode == "RGBA":
        img = img.convert("RGB")
    img.save(wallpaper_path, "JPEG", quality=JPEG_QUALITY)
    print(f"  OK Saved to staging/wallpaper.jpg")

    # 4. Process each viewport
    samples = []
    for vp in VIEWPORTS:
        # Simulate CSS background-size: cover; background-position: center
        scale = max(vp["vp_w"] / raw_w, vp["vp_h"] / raw_h)
        off_x = (vp["vp_w"] - raw_w * scale) / 2
        off_y = (vp["vp_h"] - raw_h * scale) / 2

        # The benchmark region is defined on raw 1920x1080 wallpaper.
        # All viewports sample the exact same raw pixels via SRC_X/Y/W/H.
        crop_x = max(0, min(SRC_X, raw_w - 1))
        crop_y = max(0, min(SRC_Y, raw_h - 1))
        crop_w = min(SRC_W, raw_w - crop_x)
        crop_h = min(SRC_H, raw_h - crop_y)

        if crop_w <= 0 or crop_h <= 0:
            print(f"  [SKIP] {vp['name']}: invalid crop region")
            continue

        # Crop a COPY — original img unchanged
        crop = img.crop((crop_x, crop_y, crop_x + crop_w, crop_y + crop_h))
        brightness, pixel_count = compute_brightness(crop)

        samples.append({
            "name": vp["name"],
            "vp_w": vp["vp_w"],
            "vp_h": vp["vp_h"],
            "dpi_scale": vp["dpi_scale"],
            "cx": BENCHMARK_CX,
            "cy": BENCHMARK_CY,
            "w": SRC_W,
            "h": SRC_H,
            "brightness": round(brightness, 1),
            "pixel_count": pixel_count,
        })
        print(f"  {vp['name']}: brightness={brightness:.1f}  ({pixel_count} px)")

    if not samples:
        print("[FATAL] No valid samples collected.")
        sys.exit(1)

    # 5. Overall verdict: median of all viewport brightnesses
    overall = median([s["brightness"] for s in samples])
    logo = "dark" if overall >= BRIGHTNESS_THRESHOLD else "white"
    print(f"\nOverall brightness: {overall:.1f}  ->  logo={logo}")

    # 6. Write logo_config.js to staging/
    write_config(samples, overall, logo, raw_w, raw_h)
    print(f"  OK Wrote staging/{CONFIG_FILE}")

    # 7. Atomic replacement: staging/ -> prod/
    #    Uses rename (not rmtree) to bypass Windows VS Code file locks.
    #    GitHub Actions (Ubuntu) won't have this issue, but rename works everywhere.
    PROD_OLD = os.path.join(SCRIPT_DIR, "prod_old")

    # Clean up any leftover prod_old
    if os.path.exists(PROD_OLD):
        shutil.rmtree(PROD_OLD)

    # Rename old prod -> prod_old (avoids rmtree PermissionError on Windows)
    if os.path.exists(PROD_DIR):
        os.rename(PROD_DIR, PROD_OLD)

    # Rename staging -> prod (atomic on same filesystem)
    os.rename(STAGING_DIR, PROD_DIR)

    # Clean up old prod (ignore Windows file-lock errors)
    if os.path.exists(PROD_OLD):
        try:
            shutil.rmtree(PROD_OLD)
        except PermissionError:
            print(f"  (cleanup note: prod_old/ locked by OS, will be removed next run)")

    print(f"\n[OK] Atomic replacement: staging/ -> prod/")
    print(f"     Wallpaper: {WALLPAPER_FILE}")
    print(f"     Config:    {CONFIG_FILE}")


if __name__ == "__main__":
    main()
