"""
Bing Wallpaper Download & Logo Brightness Detection Script
Usage: python update_wallpaper.py
  1. Download today's Bing wallpaper (1920x1080)
  2. Crop Logo area from a copy using user-measured rectangle
  3. Compute WCAG relative luminance → dark/white logo decision
  4. Atomically replace staging/ → prod/
"""
import json
import os
import sys
import io
import shutil
import urllib.request
import urllib.error
import time
from io import BytesIO

# Fix encoding for Windows CMD
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

try:
    from PIL import Image
except ImportError:
    print("[ERROR] Pillow not installed. Run: pip install Pillow")
    sys.exit(1)

# ── Configuration ──────────────────────────────────────────────

API_URL = "https://api.dujin.org/bing/1920.php"
API_FALLBACK = "https://bing.bitdata.top/api/wallpaper?format=image"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
STAGING_DIR = os.path.join(SCRIPT_DIR, "staging")
PROD_DIR = os.path.join(SCRIPT_DIR, "prod")
CONFIG_FILE = "logo_config.js"
WALLPAPER_FILE = "wallpaper.jpg"

# User-measured crop rectangle on 1920x1080 wallpaper
# cx=960, cy=305, w=400, h=160 → srcX=760, srcY=225
CROP_X = 760
CROP_Y = 225
CROP_W = 400
CROP_H = 160
CROP_FILE = "crop.jpg"

BRIGHTNESS_THRESHOLD = 150   # ≥150 → dark logo, <150 → white logo
JPEG_QUALITY = 92

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
}


# ── Helpers ────────────────────────────────────────────────────

def download_wallpaper(url, timeout=30):
    """Download wallpaper bytes from URL, following redirects."""
    req = urllib.request.Request(url, headers=HEADERS)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            data = resp.read()
            if len(data) < 10 * 1024:
                raise ValueError(f"Image too small: {len(data)} bytes")
            return data
    except Exception as e:
        raise RuntimeError(f"Download failed: {e}")


def compute_brightness(crop_img):
    """Compute WCAG relative luminance of a cropped image.
    Only counts pixels with alpha >= 128.
    Returns (average_luminance, pixel_count).
    """
    if crop_img.mode == "RGBA":
        pixels = list(crop_img.getdata())
    else:
        pixels = [(r, g, b, 255) for (r, g, b) in crop_img.getdata()]

    total = 0.0
    count = 0
    for r, g, b, a in pixels:
        if a < 128:
            continue
        # WCAG Relative Luminance = 0.2126R + 0.7152G + 0.0722B
        total += 0.2126 * r + 0.7152 * g + 0.0722 * b
        count += 1

    if count == 0:
        return 0.0, 0
    return total / count, count


def write_config(brightness, pixel_count, logo, img_w, img_h):
    """Write logo_config.js to staging directory."""
    config = {
        "date": time.strftime("%Y-%m-%d", time.gmtime()),
        "wallpaper_raw_w": img_w,
        "wallpaper_raw_h": img_h,
        "logo": logo,
        "foot_color": "rgba(0, 0, 0, 0.8)" if logo == "dark" else "rgba(255, 255, 255, 0.8)",
        "brightness": round(brightness, 1),
        "pixel_count": pixel_count,
        "crop": {"x": CROP_X, "y": CROP_Y, "w": CROP_W, "h": CROP_H},
        "threshold": BRIGHTNESS_THRESHOLD,
        "formula": "WCAG Relative (0.2126R + 0.7152G + 0.0722B)",
    }
    content = "/* Auto-generated by update_wallpaper.py - DO NOT EDIT */\n"
    content += "var __LOGO_CONFIG__ = " + json.dumps(config, ensure_ascii=False) + ";\n"
    os.makedirs(STAGING_DIR, exist_ok=True)
    path = os.path.join(STAGING_DIR, CONFIG_FILE)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


# ── Main ───────────────────────────────────────────────────────

def main():
    # 1. Download wallpaper
    print("Downloading wallpaper...")
    try:
        img_bytes = download_wallpaper(API_URL)
        print(f"  OK {len(img_bytes) // 1024} KB from primary API")
    except Exception as e:
        print(f"  Primary API failed: {e}")
        print(f"  Trying fallback...")
        try:
            img_bytes = download_wallpaper(API_FALLBACK)
            print(f"  OK {len(img_bytes) // 1024} KB from fallback API")
        except Exception as e2:
            print(f"[FATAL] Both APIs failed. Fallback: {e2}")
            sys.exit(1)

    # 2. Open image & verify resolution
    img = Image.open(BytesIO(img_bytes))
    raw_w, raw_h = img.size
    print(f"Wallpaper size: {raw_w}x{raw_h}")
    if (raw_w, raw_h) != (1920, 1080):
        print(f"  [WARN] Non-standard resolution (expected 1920x1080)")

    # 3. Save original wallpaper to staging/
    os.makedirs(STAGING_DIR, exist_ok=True)
    wallpaper_path = os.path.join(STAGING_DIR, WALLPAPER_FILE)
    if img.mode == "RGBA":
        img = img.convert("RGB")
    img.save(wallpaper_path, "JPEG", quality=JPEG_QUALITY)
    print(f"  OK Saved to staging/wallpaper.jpg")

    # 4. Copy & crop the Logo region (clone → crop, original untouched)
    crop = img.copy().crop((CROP_X, CROP_Y, CROP_X + CROP_W, CROP_Y + CROP_H))
    brightness, pixel_count = compute_brightness(crop)
    print(f"Crop region ({CROP_X},{CROP_Y},{CROP_W},{CROP_H}): brightness={brightness:.1f} ({pixel_count} px)")

    # Save cropped image to staging/
    crop_path = os.path.join(STAGING_DIR, CROP_FILE)
    if crop.mode == "RGBA":
        crop = crop.convert("RGB")
    crop.save(crop_path, "JPEG", quality=JPEG_QUALITY)
    print(f"  OK Saved to staging/{CROP_FILE}")

    # 5. Decide logo color
    logo = "dark" if brightness >= BRIGHTNESS_THRESHOLD else "white"
    print(f"Verdict: brightness={brightness:.1f} >= threshold={BRIGHTNESS_THRESHOLD}? "
          f"{'Yes' if logo == 'dark' else 'No'} → logo={logo}")

    # 6. Write logo_config.js to staging/
    write_config(brightness, pixel_count, logo, raw_w, raw_h)
    print(f"  OK Wrote staging/{CONFIG_FILE}")

    # 7. Atomic replacement: staging/ → prod/
    PROD_OLD = os.path.join(SCRIPT_DIR, "prod_old")

    if os.path.exists(PROD_OLD):
        shutil.rmtree(PROD_OLD)

    if os.path.exists(PROD_DIR):
        os.rename(PROD_DIR, PROD_OLD)

    os.rename(STAGING_DIR, PROD_DIR)

    if os.path.exists(PROD_OLD):
        try:
            shutil.rmtree(PROD_OLD)
        except PermissionError:
            print(f"  (cleanup note: prod_old/ locked by OS, will be removed next run)")

    print(f"\n[OK] Atomic replacement: staging/ → prod/")
    print(f"     Wallpaper: {WALLPAPER_FILE}")
    print(f"     Config:    {CONFIG_FILE}")


if __name__ == "__main__":
    main()
