/* Auto-generated by CF Workers - DO NOT EDIT */
var __LOGO_CONFIG__ = {
  "date": "2026-06-23",
  "wallpaper_raw_w": 1920,
  "wallpaper_raw_h": 1080,
  "brightness": 129.1,
  "pixel_count": 11645,
  "crop": {
    "x": 760,
    "y": 225,
    "w": 400,
    "h": 160
  },
  "formula": "WCAG Relative via Cloudflare Workers"
};
